estruturação dos dados
matheussn/k-nn pull request #2
Opened 2019-09-22 20:04 UTC by mbosprates

2019-09-22 21:31 UTC, matheussn requested changes

2019-09-22 21:31 UTC, matheussn commented on estruturacao.py
> +	test = [ x.replace("\n", "").split(" ") for x in test]
O que acha de utilizar somente o `split()`, chamando ele sem passar parâmetros ele já realiza o split nos " " e "\n"
algo como:
```suggestion
	test = [x.split() for x in test]
```

2019-09-22 21:31 UTC, matheussn commented on estruturacao.py
> +	del test[0]
Talvez seja interessante salvar a primeira linha! Já que vamos precisar dela para calcular a porcentagem de acerto.

2019-09-22 21:31 UTC, matheussn commented on estruturacao.py
> +		test1.append([float(x) for x in lista[y]])
Mano, tu consegue ver que estamos iterando duas vezes nesses arrays gigantes??
O que acha de fazer uma função que recebe um array de strings e já converte os primeiros valores para float e o ultimo para int? Pois ai não precisaríamos fazer esse for.
algo como: 
```suggestion
	lambda x: [float(x) if arr.index(x) < len(arr) - 1 else int(x) for x in arr]
```
sem a anotação de lambda, e sim como uma função normal.

2019-09-22 21:31 UTC, matheussn commented on estruturacao.py
> +	test = [ x.replace("\n", "").split(" ") for x in test]
Considerando o comentário lá em baixo, da função que já retorna o array com floats e int. podemos chamar essa função aqui! Já passando o split como parâmetro.

```suggestion
	test = [convert_to_number(x.split()) for x in test]
```

2019-09-22 21:31 UTC, matheussn commented on estruturacao.py
> +	totalLinhas = len(test)
Concorda que se não deletarmos a primeira linha do arquivo não precisaremos calcular o tamanho?

2019-09-22 21:31 UTC, matheussn commented on estruturacao.py
> +	d = dimensao(test1[0])
Aqui também! Se não deletarmos a primeira linha, teremos a dimensão de cada linha.

2019-09-23 19:09 UTC, matheussn commented on estruturacao.py
> +		test1.append([float(x) for x in lista[y]])
Tem até uma forma melhor do que essa! Sem ficar calculando o `len(arr)` a cada iteração.

2019-09-24 23:08 UTC, matheussn approved these changes

2019-09-24 23:09 UTC, admrodrigo2 approved these changes

2019-09-24 23:09 UTC, admrodrigo2 commented on estruturacao.py
> +	return test
Faltou fechar o arquivo

2019-09-24 23:09 UTC, admrodrigo2 commented on estruturacao.py
> +	if len(sys.argv) < 2:
Acho que podia colocar as funções separadas do main

2019-09-24 23:11 UTC, merged